services:
  frontend:
    build: ./frontend
    container_name: yelpcamp_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
  backend:
    build: ./backend
    container_name: yelpcamp_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./app/node_modules